[package]
name = "aixm-rs"
version = "0.1.0"
authors = ["Brent Lemons <brent.lemons@fltck.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
